### ISSUE TITLE
Search Products implementation

### ISSUE THREAD

**Issue by manasi-mulay** [manasi-mulay/ecommerce-website#8]
We have plenty products in a plenty category, how can we implement search functionality?

_Originally posted by @blue-canvas in https://github.com/blue-canvas/ecommerce-website/discussions/7_

**Comment by blue-canvas** [comment]
Can I work on this ?

**Comment by cmulay** [comment]
I would like to work on this issue.

**Comment by blue-canvas** [comment]
> I would like to work on this issue.

Thanks, Keep me updated. 
Check slack for product details.
